//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public Заказ()
        {
            this.Список_заказа = new HashSet<Список_заказа>();
        }
    
        public int Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Код_пункта_выдачи { get; set; }
        public int Код_пользователя { get; set; }
        public string Код_для_получения { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
        public virtual ICollection<Список_заказа> Список_заказа { get; set; }
    }
}
