//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункты_выдачи
    {
        public Пункты_выдачи()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Код { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
