//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.Список_заказа = new HashSet<Список_заказа>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public decimal Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория { get; set; }
        public Nullable<int> Скидка { get; set; }
        public int Количествво { get; set; }
        public string Описание { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<Список_заказа> Список_заказа { get; set; }
    }
}
